Feature/list permits
ValtteriT/Spork pull request #1
Opened 2022-04-08 09:26 UTC by ValtteriT

Listing own vehicles In html table

2022-04-08 10:20 UTC, MathiasVM commented on src/main/java/com/valuemotive/lemon/CarTypeEnum.java
>  	Electric, gasoline
Enums should be in all capital letters

2022-04-08 10:36 UTC, Bizhop commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	private Map<CarTypeEnum, List<ParkingSlot>> nbSlot;
Make this final and initialize on the same line

2022-04-08 10:36 UTC, Bizhop commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	public Map<CarTypeEnum, List<ParkingSlot>> getNbSlot() {
Remove these

2022-04-08 10:37 UTC, Bizhop commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	private Map<CarTypeEnum, List<ParkingSlot>> nbSlot;
References can be direct inside the class, so no need for getter

2022-04-08 10:38 UTC, Bizhop commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	public static ParkingBuilder builder() {
Remove this

2022-04-08 11:03 UTC, jantuomi-valuemotive approved these changes

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	private Map<CarTypeEnum, List<ParkingSlot>> nbSlot;
```suggestion
	private Map<CarTypeEnum, List<ParkingSlot>> nbSlotMap;
```

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/Parking.java
>  			car.setCheckinDate(LocalDateTime.now());
ParkingSlot should store this information, not Car

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/Parking.java
>  		return slot;
Confusing API, maybe return true or false <-> succeeded, failed?

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/Parking.java
>  	}
Return true/false, or void and throw error on failure

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/ParkingBuilder.java
>  public class ParkingBuilder {
No need for builder pattern, remove

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/ParkingException.java
>  public class ParkingException extends IllegalArgumentException {
Extend some generic Exception type

2022-04-08 11:03 UTC, ghost commented on src/main/java/com/valuemotive/lemon/ParkingManager.java
> +
Ids/random not required since parking slot object does not need ID

2022-04-08 11:03 UTC, jantuomi-valuemotive commented on src/main/java/com/valuemotive/lemon/ParkingManager.java
>  			return Optional.empty();
Move null check to call site i.e. where this function is called. This function should only accept defined lists

2022-04-08 11:03 UTC, jantuomi-valuemotive commented on src/main/java/com/valuemotive/lemon/ParkingSlot.java
> +		this.setNumber(ParkingManager.generateId());
No need for ID (see above)

2022-04-08 11:03 UTC, jantuomi-valuemotive commented on src/main/java/com/valuemotive/lemon/login/pageController.java
> +}
Missing newline

2022-04-08 11:03 UTC, jantuomi-valuemotive commented on src/main/java/com/valuemotive/lemon/login/pageController.java
> +	public String myvehicles() {
```suggestion
	public String myVehicles() {
```

2022-04-08 11:03 UTC, jantuomi-valuemotive commented on src/main/java/com/valuemotive/lemon/login/pageController.java
> +	public String addvehicle(@RequestBody Input input) {
```suggestion
	public String addVehicle(@RequestBody Input input) {
```

2022-04-08 12:29 UTC, MathiasVM requested changes

2022-04-08 12:29 UTC, MathiasVM commented on src/main/java/com/valuemotive/lemon/LemonApplication.java
>  public class LemonApplication {
Perhaps a better describing name should be used. E.g "ParkingManagerApplication"

2022-04-08 12:29 UTC, MathiasVM commented on src/main/java/com/valuemotive/lemon/CarBuilder.java
> +public class CarBuilder {
This class is extra and can be removed.

2022-04-08 12:29 UTC, MathiasVM commented on src/main/java/com/valuemotive/lemon/Car.java
>  	private LocalDateTime checkinDate;
checkinDate and checkoutDate should be moved out from the Car class

2022-04-12 07:49 UTC, ValtteriT reviewed
proposed changes made

2022-04-12 07:54 UTC, merged